In [2]:
import cv2
import tensorflow as tf
import numpy as np
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)
    
CATEGORIES = ["Normal", "Not Normal"]
model = tf.keras.models.load_model("MK2ECG_Arrythmia&NSR.model")

Num GPUs Available:  1
1 Physical GPUs, 1 Logical GPUs


In [3]:
#Test the model with an example
import tkinter as tk
from tkinter import filedialog

root = tk.Tk()
root.withdraw()

file_path = filedialog.askopenfilename()
print(file_path)

x_SIZE = 335
y_SIZE = 192
img_array = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
resized_array = cv2.resize(img_array, (x_SIZE, y_SIZE))
processed_image = np.array(resized_array).reshape(-1, x_SIZE, y_SIZE, 1)


print(processed_image)

C:/Users/WJI/Pictures/ECG sample.png
[[[[ 78]
   [  1]
   [  0]
   ...
   [  2]
   [ 46]
   [  2]]

  [[  6]
   [  2]
   [ 19]
   ...
   [  1]
   [ 46]
   [  2]]

  [[  2]
   [  1]
   [ 37]
   ...
   [128]
   [  2]
   [  2]]

  ...

  [[  1]
   [ 31]
   [  2]
   ...
   [  2]
   [  2]
   [ 21]]

  [[  1]
   [  2]
   [  2]
   ...
   [  1]
   [  1]
   [  6]]

  [[  2]
   [  2]
   [  4]
   ...
   [  2]
   [ 53]
   [ 11]]]]


In [4]:
prediction = model.predict([processed_image])
print(prediction)  # will be a list in a list.


[[0.]]


In [5]:
print(CATEGORIES[int(prediction[0][0])])

Normal
